version: '3.8'
services:
  mongodb:
    image: mongo:5.0.9
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
networks:
  mongodb_network:
volumes:
  mongodb_data: